name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: JDK 설정 (Java 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle 캐싱 (속도 향상)
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Gradle Wrapper 다운로드 (필요한 경우)
        run: |
          if [ ! -f gradlew ]; then
            echo "gradlew 파일이 없습니다. Gradle Wrapper를 다시 생성합니다."
            ./gradlew wrapper
          fi

      - name: Gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Debug APK 빌드
        run: ./gradlew assembleDebug

      - name: 빌드된 APK 업로드
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
